services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: foretell
      POSTGRES_PASSWORD: foretell
      POSTGRES_DB: foretell
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
